spring:
  application:
    name: Tilas
  # ============ 数据库配置 ============
  datasource:
    # 基本连接信息
    url: jdbc:mysql://localhost:3306/tilas?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 1MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: jerry-java-ai-1104
    region: cn-beijing